### ISSUE TITLE
add metrics grid to metrics tab

### ISSUE THREAD

**Issue by pashagolub** [cybertec-postgresql/pgwatch#102]
- [x] #103
- [x] Add metrics grid
- [x] #104
- [x] #106
- [x] Comment columns
- [x] Enabled column
- [x] Is helper column
- [x] Modified column
- [x] Edit button
- [x] Delete button
- [x] Show SQL button
