### ISSUE TITLE
implement `POST /metric` & `PATCH /metric` to web-UI

### ISSUE THREAD

**Issue by denys-holub** [cybertec-postgresql/pgwatch#119]
- [x] create modal form for creating/editing metrics
- [x] implement `POST /metric`
- [x] implement `PATCH /metric`
