### ISSUE TITLE
make GridActions & GridToolbar components common

### ISSUE THREAD

**Issue by denys-holub** [cybertec-postgresql/pgwatch#129]
- [ ] make GridActionsComponent common
- [ ] make GridToolbarComponent common
- [ ] create separate file with functions that returns grid columns
