### ISSUE TITLE
add `Preset configs` tab

### ISSUE THREAD

**Issue by denys-holub** [cybertec-postgresql/pgwatch#135]
- [x] add `Preset configs` tab
- [x] add grid for preset configs
- [x] implement `GET /preset`
