### ISSUE TITLE
add support for Log tab in web UI

### ISSUE THREAD

**Issue by pashagolub** [cybertec-postgresql/pgwatch#170]
- [x] add `GET /log` REST API endpoint on back-end
- [x] implement log displaying on front-end
- [ ] ~~implement **Search** on front-end~~
- [ ] ~~implement **Filter** on front-end~~
