### ISSUE TITLE
new Dockerfile based on official Postgres image

### ISSUE THREAD

**Issue by pashagolub** [cybertec-postgresql/pgwatch#210]
- [ ] use `FROM postgres:15` as final image
- [ ] put bootstrap files into `/docker-entrypoint-initdb.d` for automatic provision
- [ ] remove unused `src` files from the final image
- [ ] rename files to force order of the execution, see [Initialization scripts](https://hub.docker.com/_/postgres) section
- [ ] get rid of `docker-launcher-*` scripts
